language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
   #Uses miniconda installation of scientific python packages instead of building from source
   #or using old versions supplied by apt-get. Source: https://gist.github.com/dan-blanchard/7045057
   - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh; fi
   - chmod +x miniconda.sh
   - ./miniconda.sh -b
   - export PATH=/home/travis/miniconda3/bin:/home/travis/miniconda2/bin:$PATH
   - conda update --yes conda
   - sudo apt-get update -qq
   - sudo apt-get install -qq build-essential libgsl0-dev bedtools mummer
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


  - conda install --yes python=$TRAVIS_PYTHON_VERSION cython numpy scipy biopython pandas pip scikit-learn docutils sphinx jinja2 seaborn
  - pip install bcbio-gff
  - python setup.py install
# command to run tests
script:
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_CONCOCT_38d2d86944_1
  - python -m properform Push 47.88.50.110:15554 asdf_CONCOCT_38d2d86944_1 ./profile_CONCOCT_38d2d86944_1
 #2017-09-16 13:02:43 modified at 0 #2017-09-16 13:02:47 modified at 1